version: "3.8"

services:
  admin:
    build: .
    container_name: admin-template
    environment:
      PORT: 3002
      API_URL: http://host.docker.internal:5000
    ports:
      - "3002:3002"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 384M
        reservations:
          cpus: "0.25"
          memory: 128M
