import { ContactRound, Users } from "lucide-react";
import { useFormContext } from "react-hook-form";
import { localizedInputDirection } from "@/lib/localized-direction";
import { SectionCard } from "@/pages/home/components/SectionCard";
import type { RouteContentCopyText } from "../route-content-copy";
import type { RouteContentFormValues, RouteContentLocale } from "../types";
import { FormField, Input, Textarea } from "./RepeatableControls";

export function TeamPeopleContentFields({ locale, copy }: { locale: RouteContentLocale; copy: RouteContentCopyText }) {
  const { register } = useFormContext<RouteContentFormValues>();
  const prefix = `translations.${locale}.team-people.teamPeople` as const;
  return <div className={localizedInputDirection(locale)}><SectionCard title={copy.teamLabels} icon={Users}><div className="grid gap-4 md:grid-cols-2"><FormField label={copy.memberLabel}><Input {...register(`${prefix}.memberLabel`)} /></FormField><FormField label={copy.openProfile}><Input {...register(`${prefix}.openProfileLabel`)} /></FormField><FormField label={copy.backToTeam}><Input {...register(`${prefix}.backToTeamLabel`)} /></FormField><FormField label={copy.closeProfile}><Input {...register(`${prefix}.closeProfileLabel`)} /></FormField><FormField label={copy.linkedIn}><Input {...register(`${prefix}.linkedInLabel`)} /></FormField><FormField label={copy.previous}><Input {...register(`${prefix}.previousMemberLabel`)} /></FormField><FormField label={copy.next}><Input {...register(`${prefix}.nextMemberLabel`)} /></FormField><FormField label={copy.emptyMessage} className="md:col-span-2"><Textarea {...register(`${prefix}.emptyMessage`)} /></FormField></div></SectionCard></div>;
}

export function TeamCareersContentFields({ locale, copy }: { locale: RouteContentLocale; copy: RouteContentCopyText }) {
  const { register } = useFormContext<RouteContentFormValues>();
  const prefix = `translations.${locale}.team-careers.teamCareers` as const;
  return <div className={localizedInputDirection(locale)}><SectionCard title={copy.careersForm} icon={ContactRound}><div className="grid gap-4 md:grid-cols-2"><FormField label={copy.privacyNote} className="md:col-span-2"><Textarea {...register(`${prefix}.privacy`)} /></FormField><FormField label={copy.successTitle}><Input {...register(`${prefix}.successTitle`)} /></FormField><FormField label={copy.successMessage}><Textarea {...register(`${prefix}.successBody`)} /></FormField><FormField label={copy.name}><Input {...register(`${prefix}.nameLabel`)} /></FormField><FormField label={copy.email}><Input {...register(`${prefix}.emailLabel`)} /></FormField><FormField label={copy.phone}><Input {...register(`${prefix}.phoneLabel`)} /></FormField><FormField label={copy.role}><Input {...register(`${prefix}.roleLabel`)} /></FormField><FormField label={copy.rolePlaceholder}><Input {...register(`${prefix}.rolePlaceholder`)} /></FormField><FormField label={copy.linkedIn}><Input {...register(`${prefix}.linkedInLabel`)} /></FormField><FormField label={`${copy.linkedIn} · ${copy.placeholder}`}><Input {...register(`${prefix}.linkedInPlaceholder`)} /></FormField><FormField label={copy.portfolio}><Input {...register(`${prefix}.portfolioLabel`)} /></FormField><FormField label={`${copy.portfolio} · ${copy.placeholder}`}><Input {...register(`${prefix}.portfolioPlaceholder`)} /></FormField><FormField label={copy.note}><Input {...register(`${prefix}.noteLabel`)} /></FormField><FormField label={copy.cv}><Input {...register(`${prefix}.cvLabel`)} /></FormField><FormField label={copy.cvHint} className="md:col-span-2"><Textarea {...register(`${prefix}.cvHint`)} /></FormField><FormField label={copy.errorMessage} className="md:col-span-2"><Textarea {...register(`${prefix}.errorMessage`)} /></FormField><FormField label={copy.submitting}><Input {...register(`${prefix}.submittingLabel`)} /></FormField><FormField label={copy.submit}><Input {...register(`${prefix}.submitLabel`)} /></FormField></div></SectionCard></div>;
}
