import type { Lang } from "@/context/global";

const en = {
  title: "Home experience",
  description: "Edit every public Home section, translation, call to action, and image from one place.",
  save: "Publish changes",
  saving: "Saving…",
  publishing: "Publishing",
  draft: "Draft",
  archived: "Archived",
  visibility: "Visible sections",
  general: "Publishing & visibility",
  hero: "Hero",
  partners: "Trusted partners",
  painPoints: "Pain points",
  services: "Services introduction",
  testimonials: "Testimonials",
  badge: "Badge",
  heading: "Heading",
  subheading: "Subheading",
  image: "Main image",
  background: "Background image",
  currentUrl: "Current image URL",
  upload: "Upload replacement",
  imageHint: "PNG, JPG, or WEBP · maximum 5 MB",
  labels: "Visual labels",
  tags: "Capability tags",
  sceneLabels: "Scene labels",
  scenePrimaryLabel: "Primary scene label",
  sceneSecondaryLabel: "Secondary scene label",
  capabilitiesLabel: "Capabilities rail label",
  primaryCta: "Primary action",
  secondaryCta: "Secondary action",
  label: "Label",
  link: "Link",
  stats: "Hero statistics",
  value: "Value",
  partner: "Partner",
  name: "Name",
  category: "Category",
  addPartner: "Add partner",
  remove: "Remove",
  painPoint: "Pain point",
  descriptionLabel: "Description",
  cta: "Closing message",
  emptyMessage: "Empty-state message",
  errorMessage: "Error message",
  testimonial: "Testimonial",
  quote: "Quote",
  personTitle: "Person / role title",
  addTestimonial: "Add testimonial",
  languageHint: "Edit English, Arabic, and Turkish without leaving the form.",
} as const;

export type HomeCopy = Record<keyof typeof en, string>;
export const HOME_COPY: Record<Lang, HomeCopy> = {
  en,
  ar: {
    title: "تجربة الصفحة الرئيسية", description: "حرّر جميع أقسام الصفحة الرئيسية والترجمات والأزرار والصور من مكان واحد.", save: "نشر التغييرات", saving: "جارٍ الحفظ…", publishing: "منشور", draft: "مسودة", archived: "مؤرشف", visibility: "الأقسام الظاهرة", general: "النشر والظهور", hero: "الواجهة الرئيسية", partners: "الشركاء الموثوقون", painPoints: "التحديات", services: "مقدمة الخدمات", testimonials: "آراء العملاء", badge: "الشارة", heading: "العنوان", subheading: "العنوان الفرعي", image: "الصورة الرئيسية", background: "صورة الخلفية", currentUrl: "رابط الصورة الحالي", upload: "رفع صورة بديلة", imageHint: "PNG أو JPG أو WEBP · بحد أقصى 5 ميغابايت", labels: "التسميات البصرية", tags: "وسوم القدرات", sceneLabels: "تسميات المشهد", scenePrimaryLabel: "تسمية المشهد الأولى", sceneSecondaryLabel: "تسمية المشهد الثانية", capabilitiesLabel: "تسمية شريط القدرات", primaryCta: "الإجراء الرئيسي", secondaryCta: "الإجراء الثانوي", label: "النص", link: "الرابط", stats: "إحصاءات الواجهة", value: "القيمة", partner: "الشريك", name: "الاسم", category: "التصنيف", addPartner: "إضافة شريك", remove: "إزالة", painPoint: "التحدي", descriptionLabel: "الوصف", cta: "الرسالة الختامية", emptyMessage: "رسالة الحالة الفارغة", errorMessage: "رسالة الخطأ", testimonial: "رأي العميل", quote: "الاقتباس", personTitle: "المنصب / الصفة", addTestimonial: "إضافة رأي", languageHint: "حرّر الإنجليزية والعربية والتركية دون مغادرة النموذج.",
  },
  tr: {
    title: "Ana sayfa deneyimi", description: "Tüm ana sayfa bölümlerini, çevirileri, eylemleri ve görselleri tek yerden düzenleyin.", save: "Değişiklikleri yayınla", saving: "Kaydediliyor…", publishing: "Yayında", draft: "Taslak", archived: "Arşivlendi", visibility: "Görünür bölümler", general: "Yayın ve görünürlük", hero: "Karşılama alanı", partners: "Güvenilir ortaklar", painPoints: "Sorunlar", services: "Hizmetler girişi", testimonials: "Müşteri görüşleri", badge: "Rozet", heading: "Başlık", subheading: "Alt başlık", image: "Ana görsel", background: "Arka plan görseli", currentUrl: "Mevcut görsel URL'si", upload: "Yeni görsel yükle", imageHint: "PNG, JPG veya WEBP · en fazla 5 MB", labels: "Görsel etiketler", tags: "Yetenek etiketleri", sceneLabels: "Sahne etiketleri", scenePrimaryLabel: "Birincil sahne etiketi", sceneSecondaryLabel: "İkincil sahne etiketi", capabilitiesLabel: "Yetenek bandı etiketi", primaryCta: "Birincil eylem", secondaryCta: "İkincil eylem", label: "Etiket", link: "Bağlantı", stats: "Karşılama istatistikleri", value: "Değer", partner: "Ortak", name: "Ad", category: "Kategori", addPartner: "Ortak ekle", remove: "Kaldır", painPoint: "Sorun", descriptionLabel: "Açıklama", cta: "Kapanış mesajı", emptyMessage: "Boş durum mesajı", errorMessage: "Hata mesajı", testimonial: "Müşteri görüşü", quote: "Alıntı", personTitle: "Kişi / rol unvanı", addTestimonial: "Görüş ekle", languageHint: "İngilizce, Arapça ve Türkçe içeriği formdan ayrılmadan düzenleyin.",
  },
};
