import type { ResourceConfig } from "./types";

const publishStatuses = ["DRAFT", "PUBLISHED", "ARCHIVED"] as const;

export const RESOURCE_CONFIGS = {
  pages: {
    key: "pages",
    title: "Pages",
    description: "Manage page metadata and its database-backed translations.",
    endpoint: "/pages",
    adminPath: "/pages",
    fields: [
      { name: "kind", label: "Page kind", kind: "select", options: ["HOME", "STANDARD", "LANDING", "LEGAL"] },
      { name: "status", label: "Status", kind: "select", options: publishStatuses },
      { name: "template", label: "Template" },
      { name: "sortOrder", label: "Sort order", kind: "number" },
      { name: "isHomePage", label: "Home page", kind: "boolean" },
    ],
    translationFields: [
      { name: "title", label: "Title", required: true },
      { name: "navigationLabel", label: "Navigation label" },
      { name: "excerpt", label: "Excerpt", kind: "textarea", wide: true },
      { name: "metaTitle", label: "SEO title" },
      { name: "metaDescription", label: "SEO description", kind: "textarea", wide: true },
    ],
    columns: [{ field: "slug", label: "Slug" }, { field: "kind", label: "Kind" }, { field: "status", label: "Status" }],
    displayField: "slug",
  },
  services: {
    key: "services",
    title: "Services",
    description: "Manage services and localized public content.",
    endpoint: "/services",
    adminPath: "/services",
    fields: [
      { name: "icon", label: "Icon" },
      { name: "status", label: "Status", kind: "select", options: publishStatuses },
      { name: "sortOrder", label: "Sort order", kind: "number" },
      { name: "isFeatured", label: "Featured", kind: "boolean" },
    ],
    translationFields: [
      { name: "title", label: "Title", required: true },
      { name: "subtitle", label: "Subtitle" },
      { name: "description", label: "Description", kind: "textarea", wide: true },
      { name: "audience", label: "Audience", kind: "textarea" },
      { name: "approach", label: "Approach", kind: "textarea" },
      { name: "outcome", label: "Outcome", kind: "textarea", wide: true },
    ],
    columns: [{ field: "slug", label: "Slug" }, { field: "status", label: "Status" }, { field: "isFeatured", label: "Featured" }],
    displayField: "slug",
  },
  projects: {
    key: "projects",
    title: "Projects",
    description: "Manage delivery projects, visibility, progress and case-study translations.",
    endpoint: "/projects",
    adminPath: "/projects",
    fields: [
      { name: "projectNumber", label: "Project number", required: true, group: "identity" },
      { name: "name", label: "Internal name", required: true, group: "identity" },
      { name: "slug", label: "Public URL slug", group: "identity" },
      { name: "type", label: "Type", kind: "select", options: ["CLIENT", "INTERNAL", "OPEN_SOURCE", "TRAINING_CAPSTONE"], group: "identity" },
      { name: "status", label: "Status", kind: "select", options: ["PLANNING", "ACTIVE", "ON_HOLD", "IN_REVIEW", "COMPLETED", "CANCELLED", "ARCHIVED"], group: "identity" },
      { name: "visibility", label: "Visibility", kind: "select", options: ["PRIVATE", "CLIENT_ONLY", "PUBLIC"], group: "identity" },
      { name: "progressPercent", label: "Progress %", kind: "number", group: "delivery" },
      { name: "startDate", label: "Start date", kind: "date", group: "delivery" },
      { name: "targetEndDate", label: "Target end date", kind: "date", group: "delivery" },
      { name: "clientName", label: "Client / product name", group: "delivery" },
      { name: "completionYear", label: "Completion year", kind: "number", group: "delivery" },
      { name: "projectUrl", label: "Live project URL", placeholder: "https://", group: "presentation" },
      { name: "coverImageUrl", label: "Project cover", kind: "image", wide: true, group: "presentation" },
      { name: "galleryImages", label: "Gallery image URLs", kind: "list", wide: true, group: "presentation" },
      { name: "accentColor", label: "Accent color", placeholder: "#006b70", group: "presentation" },
      { name: "technologies", label: "Technologies", kind: "list", wide: true, group: "presentation" },
      { name: "sortOrder", label: "Sort order", kind: "number", group: "presentation" },
      { name: "isFeatured", label: "Featured", kind: "boolean", group: "presentation" },
    ],
    translationFields: [
      { name: "title", label: "Title", required: true, group: "overview" },
      { name: "subtitle", label: "Subtitle", group: "overview" },
      { name: "summary", label: "Summary", kind: "textarea", wide: true, group: "overview" },
      { name: "context", label: "Context", kind: "textarea", group: "story" },
      { name: "challenges", label: "Challenges", kind: "textarea", group: "story" },
      { name: "solution", label: "Solution", kind: "textarea", wide: true, group: "story" },
      { name: "services", label: "Services delivered", kind: "list", wide: true, group: "outcomes" },
      { name: "keyElements", label: "Key elements", kind: "list", group: "outcomes" },
      { name: "results", label: "Results", kind: "list", group: "outcomes" },
      { name: "impactSummary", label: "Impact summary", kind: "textarea", wide: true, group: "outcomes" },
      { name: "testimonialQuote", label: "Testimonial quote", kind: "textarea", wide: true, group: "outcomes" },
      { name: "testimonialAuthor", label: "Testimonial author", group: "outcomes" },
      { name: "metaTitle", label: "SEO title", group: "seo" },
      { name: "metaDescription", label: "SEO description", kind: "textarea", wide: true, group: "seo" },
    ],
    columns: [{ field: "projectNumber", label: "Number" }, { field: "name", label: "Name" }, { field: "status", label: "Status" }, { field: "progressPercent", label: "Progress" }],
    displayField: "name",
  },
  blog: {
    key: "blog",
    title: "Blog",
    description: "Manage localized articles and publishing metadata.",
    endpoint: "/posts",
    adminPath: "/blog",
    fields: [
      { name: "coverImageUrl", label: "Cover image", kind: "image", wide: true },
      { name: "status", label: "Status", kind: "select", options: publishStatuses },
      { name: "publishedAt", label: "Published at", kind: "date" },
      { name: "authorName", label: "Author name" },
      { name: "readMinutes", label: "Read time (minutes)", kind: "number" },
      { name: "sortOrder", label: "Sort order", kind: "number" },
      { name: "tags", label: "Tags", kind: "list", wide: true },
      { name: "isFeatured", label: "Featured", kind: "boolean" },
    ],
    translationFields: [
      { name: "title", label: "Title", required: true },
      { name: "excerpt", label: "Excerpt", kind: "textarea", wide: true },
      { name: "content", label: "Content", kind: "textarea", required: true, wide: true },
      { name: "metaTitle", label: "SEO title" },
      { name: "metaDescription", label: "SEO description", kind: "textarea", wide: true },
    ],
    columns: [{ field: "slug", label: "Slug" }, { field: "status", label: "Status" }, { field: "publishedAt", label: "Published" }],
    displayField: "slug",
  },
  training: {
    key: "training",
    title: "Training programs",
    description: "Manage programs and localized learning content.",
    endpoint: "/training/programs",
    adminPath: "/training",
    fields: [
      { name: "status", label: "Status", kind: "select", options: publishStatuses },
      { name: "level", label: "Level", kind: "select", options: ["BEGINNER", "INTERMEDIATE", "ADVANCED", "ALL_LEVELS"] },
      { name: "durationHours", label: "Duration (hours)", kind: "number" },
      { name: "sortOrder", label: "Sort order", kind: "number" },
      { name: "isFeatured", label: "Featured", kind: "boolean" },
    ],
    translationFields: [
      { name: "title", label: "Title", required: true },
      { name: "summary", label: "Summary", kind: "textarea", wide: true },
      { name: "description", label: "Description", kind: "textarea", wide: true },
      { name: "prerequisites", label: "Prerequisites", kind: "textarea" },
      { name: "outcomes", label: "Outcomes", kind: "list" },
    ],
    columns: [{ field: "slug", label: "Slug" }, { field: "status", label: "Status" }, { field: "level", label: "Level" }],
    displayField: "slug",
  },
  jobTitles: {
    key: "jobTitles",
    title: "Job titles",
    description: "Manage career role titles used by team members and applications.",
    endpoint: "/job-titles",
    adminPath: "/job-titles",
    fields: [
      { name: "sortOrder", label: "Sort order", kind: "number" },
      { name: "isActive", label: "Active", kind: "boolean" },
    ],
    translationFields: [
      { name: "title", label: "Title", required: true },
    ],
    columns: [{ field: "key", label: "Key" }, { field: "sortOrder", label: "Sort order" }, { field: "isActive", label: "Active" }],
    displayField: "key",
  },
  teamMembers: {
    key: "teamMembers",
    title: "Team members",
    description: "Manage public team members and localized biographies.",
    endpoint: "/team-members",
    adminPath: "/team-members",
    fields: [
      { name: "jobTitleKey", label: "Job title", kind: "relation", required: true, relation: { endpoint: "/job-titles/admin", valueField: "key", labelField: "title" } },
      { name: "imageUrl", label: "Member image", kind: "image", wide: true },
      { name: "linkedInUrl", label: "LinkedIn URL" },
      { name: "sortOrder", label: "Sort order", kind: "number" },
      { name: "isActive", label: "Active", kind: "boolean" },
    ],
    translationFields: [
      { name: "fullName", label: "Localized full name", required: true },
      { name: "bio", label: "Bio", kind: "textarea", wide: true },
    ],
    columns: [{ field: "fullName", label: "Name" }, { field: "jobTitleKey", label: "Job title" }, { field: "isActive", label: "Active" }],
    displayField: "fullName",
  },
  inquiries: {
    key: "inquiries",
    title: "Inquiries",
    description: "Review contact requests and update their workflow status.",
    endpoint: "/inquiries",
    adminPath: "/messages",
    protectedRead: true,
    fields: [
      { name: "fullName", label: "Full name", required: true },
      { name: "email", label: "Email", required: true },
      { name: "phone", label: "Phone" },
      { name: "organization", label: "Organization" },
      { name: "message", label: "Message", kind: "textarea", required: true, wide: true },
      { name: "status", label: "Status", kind: "select", options: ["NEW", "REVIEWING", "CONTACTED", "QUALIFIED", "PROPOSAL_SENT", "WON", "LOST", "SPAM", "ARCHIVED"] },
      { name: "internalNotes", label: "Internal notes", kind: "textarea", wide: true },
    ],
    columns: [{ field: "fullName", label: "Name" }, { field: "email", label: "Email" }, { field: "status", label: "Status" }, { field: "createdAt", label: "Received" }],
    displayField: "fullName",
  },
} satisfies Record<string, ResourceConfig>;

export type ResourceName = keyof typeof RESOURCE_CONFIGS;
