import type { Lang } from "@/context/global";
import type { ResourceName } from "./config";

const en = {
  resources: {
    pages: { title: "Pages", description: "Manage page metadata and database-backed translations." },
    services: { title: "Services", description: "Manage services and localized public content." },
    projects: { title: "Projects", description: "Manage delivery projects, visibility, progress, and case studies." },
    blog: { title: "Blog", description: "Manage localized articles and publishing metadata." },
    training: { title: "Training programs", description: "Manage programs and localized learning content." },
    jobTitles: { title: "Job titles", description: "Manage career role titles." },
    teamMembers: { title: "Team members", description: "Manage public team members and biographies." },
    inquiries: { title: "Inquiries", description: "Review contact requests and their workflow status." },
  },
  search: "Search",
  add: "Add record",
  actions: "Actions",
  edit: "Edit",
  remove: "Delete",
  noRecords: "No records match your search.",
  updateRecord: "Update record",
  newRecord: "New record",
  formHint: "Complete the details below, then save your changes.",
  general: "General information",
  generalHint: "Core settings and record details.",
  localized: "Localized content",
  localizedHint: "Add the content shown to visitors in each supported language.",
  cancel: "Cancel",
  saving: "Saving…",
  saveChanges: "Save changes",
  createRecord: "Create record",
  deleting: "Deleting…",
  deleteTitle: "Delete record?",
  deleteHint: "This permanently deletes the selected record and its translations.",
  required: "is required",
  requiredFor: "is required for",
  invalid: "Check the form values.",
  select: "Select",
  yes: "Yes",
  no: "No",
  en: "English",
  ar: "Arabic",
  tr: "Turkish",
} as const;

type BaseCopy = typeof en;
export type ResourceCopyText = {
  resources: Record<ResourceName, { title: string; description: string }>;
} & Record<Exclude<keyof BaseCopy, "resources">, string>;

export const RESOURCE_COPY: Record<Lang, ResourceCopyText> = {
  en,
  ar: {
    resources: {
      pages: { title: "الصفحات", description: "إدارة بيانات الصفحات وترجماتها المحفوظة في قاعدة البيانات." },
      services: { title: "الخدمات", description: "إدارة الخدمات والمحتوى العام المترجم." },
      projects: { title: "المشاريع", description: "إدارة المشاريع والظهور والتقدم ودراسات الحالة." },
      blog: { title: "المدونة", description: "إدارة المقالات المترجمة وبيانات النشر." },
      training: { title: "برامج التدريب", description: "إدارة البرامج والمحتوى التعليمي المترجم." },
      jobTitles: { title: "المسميات الوظيفية", description: "إدارة مسميات الوظائف." },
      teamMembers: { title: "أعضاء الفريق", description: "إدارة أعضاء الفريق والسير الذاتية." },
      inquiries: { title: "الطلبات", description: "مراجعة طلبات التواصل وحالة متابعتها." },
    },
    search: "بحث",
    add: "إضافة سجل",
    actions: "الإجراءات",
    edit: "تعديل",
    remove: "حذف",
    noRecords: "لا توجد سجلات تطابق البحث.",
    updateRecord: "تحديث السجل",
    newRecord: "سجل جديد",
    formHint: "أكمل التفاصيل ثم احفظ التغييرات.",
    general: "المعلومات العامة",
    generalHint: "الإعدادات الأساسية وتفاصيل السجل.",
    localized: "المحتوى المترجم",
    localizedHint: "أضف المحتوى الظاهر للزوار بكل لغة مدعومة.",
    cancel: "إلغاء",
    saving: "جارٍ الحفظ…",
    saveChanges: "حفظ التغييرات",
    createRecord: "إنشاء السجل",
    deleting: "جارٍ الحذف…",
    deleteTitle: "حذف السجل؟",
    deleteHint: "سيؤدي هذا إلى حذف السجل المحدد وترجماته نهائياً.",
    required: "مطلوب",
    requiredFor: "مطلوب للغة",
    invalid: "تحقق من قيم النموذج.",
    select: "اختر",
    yes: "نعم",
    no: "لا",
    en: "الإنجليزية",
    ar: "العربية",
    tr: "التركية",
  },
  tr: {
    resources: {
      pages: { title: "Sayfalar", description: "Sayfa meta verilerini ve veritabanı çevirilerini yönetin." },
      services: { title: "Hizmetler", description: "Hizmetleri ve yerelleştirilmiş genel içeriği yönetin." },
      projects: { title: "Projeler", description: "Projeleri, görünürlüğü, ilerlemeyi ve vaka çalışmalarını yönetin." },
      blog: { title: "Blog", description: "Yerelleştirilmiş yazıları ve yayın bilgilerini yönetin." },
      training: { title: "Eğitim programları", description: "Programları ve yerelleştirilmiş öğrenme içeriğini yönetin." },
      jobTitles: { title: "İş unvanları", description: "Kariyer rol başlıklarını yönetin." },
      teamMembers: { title: "Ekip üyeleri", description: "Genel ekip üyelerini ve biyografileri yönetin." },
      inquiries: { title: "Talepler", description: "İletişim taleplerini ve iş akışı durumlarını inceleyin." },
    },
    search: "Ara",
    add: "Kayıt ekle",
    actions: "İşlemler",
    edit: "Düzenle",
    remove: "Sil",
    noRecords: "Aramanızla eşleşen kayıt yok.",
    updateRecord: "Kaydı güncelle",
    newRecord: "Yeni kayıt",
    formHint: "Aşağıdaki bilgileri tamamlayın ve değişiklikleri kaydedin.",
    general: "Genel bilgiler",
    generalHint: "Temel ayarlar ve kayıt ayrıntıları.",
    localized: "Yerelleştirilmiş içerik",
    localizedHint: "Her desteklenen dilde ziyaretçilere gösterilen içeriği ekleyin.",
    cancel: "İptal",
    saving: "Kaydediliyor…",
    saveChanges: "Değişiklikleri kaydet",
    createRecord: "Kayıt oluştur",
    deleting: "Siliniyor…",
    deleteTitle: "Kayıt silinsin mi?",
    deleteHint: "Seçili kayıt ve çevirileri kalıcı olarak silinir.",
    required: "gereklidir",
    requiredFor: "şu dil için gereklidir",
    invalid: "Form değerlerini kontrol edin.",
    select: "Seç",
    yes: "Evet",
    no: "Hayır",
    en: "İngilizce",
    ar: "Arapça",
    tr: "Türkçe",
  },
};

const FIELD_LABELS: Record<Lang, Record<string, string>> = {
  en: {},
  ar: {
    slug: "المعرّف في الرابط", kind: "نوع الصفحة", status: "الحالة", template: "القالب", sortOrder: "ترتيب العرض", isHomePage: "الصفحة الرئيسية", icon: "الأيقونة", isFeatured: "مميز", key: "المفتاح", isActive: "نشط", jobTitleKey: "المسمى الوظيفي", imageUrl: "صورة العضو", coverImageUrl: "صورة الغلاف", linkedInUrl: "رابط لينكدإن", bio: "السيرة المختصرة", authorName: "اسم الكاتب", readMinutes: "مدة القراءة بالدقائق",
    projectNumber: "رقم المشروع", name: "الاسم الداخلي", type: "النوع", visibility: "الظهور", progressPercent: "نسبة التقدم", startDate: "تاريخ البدء", targetEndDate: "تاريخ الانتهاء المتوقع", technologies: "التقنيات", publishedAt: "تاريخ النشر", tags: "الوسوم", level: "المستوى", durationHours: "المدة بالساعات",
    title: "العنوان", navigationLabel: "عنوان التنقل", excerpt: "المقتطف", metaTitle: "عنوان محركات البحث", metaDescription: "وصف محركات البحث", subtitle: "العنوان الفرعي", description: "الوصف", audience: "الجمهور", approach: "النهج", outcome: "النتيجة", summary: "الملخص", context: "السياق", challenges: "التحديات", solution: "الحل", keyElements: "العناصر الأساسية", results: "النتائج", content: "المحتوى", prerequisites: "المتطلبات السابقة", outcomes: "المخرجات",
    fullName: "الاسم الكامل", email: "البريد الإلكتروني", phone: "الهاتف", organization: "المؤسسة", message: "الرسالة", internalNotes: "الملاحظات الداخلية", createdAt: "تاريخ الاستلام",
  },
  tr: {
    slug: "URL kimliği", kind: "Sayfa türü", status: "Durum", template: "Şablon", sortOrder: "Sıralama", isHomePage: "Ana sayfa", icon: "Simge", isFeatured: "Öne çıkan", key: "Anahtar", isActive: "Aktif", jobTitleKey: "İş unvanı", imageUrl: "Üye görseli", coverImageUrl: "Kapak görseli", linkedInUrl: "LinkedIn URL", bio: "Biyografi", authorName: "Yazar adı", readMinutes: "Okuma süresi (dakika)",
    projectNumber: "Proje numarası", name: "Dahili ad", type: "Tür", visibility: "Görünürlük", progressPercent: "İlerleme yüzdesi", startDate: "Başlangıç tarihi", targetEndDate: "Hedef bitiş tarihi", technologies: "Teknolojiler", publishedAt: "Yayın tarihi", tags: "Etiketler", level: "Seviye", durationHours: "Süre (saat)",
    title: "Başlık", navigationLabel: "Gezinme etiketi", excerpt: "Özet", metaTitle: "SEO başlığı", metaDescription: "SEO açıklaması", subtitle: "Alt başlık", description: "Açıklama", audience: "Hedef kitle", approach: "Yaklaşım", outcome: "Sonuç", summary: "Özet", context: "Bağlam", challenges: "Zorluklar", solution: "Çözüm", keyElements: "Temel öğeler", results: "Sonuçlar", content: "İçerik", prerequisites: "Ön koşullar", outcomes: "Kazanımlar",
    fullName: "Tam ad", email: "E-posta", phone: "Telefon", organization: "Kuruluş", message: "Mesaj", internalNotes: "Dahili notlar", createdAt: "Alındı",
  },
};

const OPTION_LABELS: Record<Lang, Record<string, string>> = {
  en: {},
  ar: { DRAFT: "مسودة", PUBLISHED: "منشور", ARCHIVED: "مؤرشف", HOME: "رئيسية", STANDARD: "قياسية", LANDING: "هبوط", LEGAL: "قانونية", CLIENT: "عميل", INTERNAL: "داخلي", OPEN_SOURCE: "مفتوح المصدر", TRAINING_CAPSTONE: "مشروع تدريبي", PLANNING: "قيد التخطيط", ACTIVE: "نشط", ON_HOLD: "معلق", IN_REVIEW: "قيد المراجعة", COMPLETED: "مكتمل", CANCELLED: "ملغى", PRIVATE: "خاص", CLIENT_ONLY: "للعميل فقط", PUBLIC: "عام", BEGINNER: "مبتدئ", INTERMEDIATE: "متوسط", ADVANCED: "متقدم", ALL_LEVELS: "كل المستويات" },
  tr: { DRAFT: "Taslak", PUBLISHED: "Yayında", ARCHIVED: "Arşivlendi", HOME: "Ana sayfa", STANDARD: "Standart", LANDING: "Açılış", LEGAL: "Yasal", CLIENT: "Müşteri", INTERNAL: "Dahili", OPEN_SOURCE: "Açık kaynak", TRAINING_CAPSTONE: "Eğitim projesi", PLANNING: "Planlanıyor", ACTIVE: "Aktif", ON_HOLD: "Beklemede", IN_REVIEW: "İncelemede", COMPLETED: "Tamamlandı", CANCELLED: "İptal edildi", PRIVATE: "Özel", CLIENT_ONLY: "Yalnızca müşteri", PUBLIC: "Herkese açık", BEGINNER: "Başlangıç", INTERMEDIATE: "Orta", ADVANCED: "İleri", ALL_LEVELS: "Tüm seviyeler" },
};

export function fieldLabel(locale: Lang, name: string, fallback: string) { return FIELD_LABELS[locale][name] ?? fallback; }
export function optionLabel(locale: Lang, value: string) { return OPTION_LABELS[locale][value] ?? value.replaceAll("_", " "); }
