import type { Lang } from "@/context/global";

const en = {
  title: "Website pages",
  description: "Open any route to manage its publishing, translated content, and search metadata.",
  pages: "routes",
  published: "Published",
  draft: "Draft",
  archived: "Archived",
  openEditor: "Open editor",
  lastUpdated: "Last updated",
  back: "All pages",
  editorDescription: "Manage this route in English, Arabic, and Turkish from one focused workspace.",
  general: "Publishing",
  generalHint: "Control status, ordering, and template settings.",
  content: "Page content",
  contentHint: "Manage navigation and introductory copy.",
  seo: "Search & sharing",
  seoHint: "Set localized titles and descriptions for discovery.",
  save: "Publish changes",
  saving: "Saving…",
  status: "Status",
  template: "Template",
  sortOrder: "Sort order",
  homePage: "Primary home page",
  homePageHint: "Use this route as the website home page.",
  titleLabel: "Page title",
  navigationLabel: "Navigation label",
  excerpt: "Introduction",
  metaTitle: "SEO title",
  metaDescription: "SEO description",
  characters: "characters",
  languageHint: "Content is stored separately for every supported language.",
  missing: "This page route does not exist in the CMS.",
  noPages: "No route pages were found.",
  previewRoute: "View route",
  en: "English",
  ar: "Arabic",
  tr: "Turkish",
} as const;

type PagesCopy = Record<keyof typeof en, string>;
export const PAGES_COPY: Record<Lang, PagesCopy> = {
  en,
  ar: {
    title: "صفحات الموقع",
    description: "افتح أي مسار لإدارة النشر والمحتوى المترجم وبيانات محركات البحث.",
    pages: "مسارات",
    published: "منشورة",
    draft: "مسودة",
    archived: "مؤرشفة",
    openEditor: "فتح المحرر",
    lastUpdated: "آخر تحديث",
    back: "كل الصفحات",
    editorDescription: "أدر هذا المسار بالعربية والإنجليزية والتركية ضمن مساحة عمل واضحة.",
    general: "النشر",
    generalHint: "تحكم بالحالة والترتيب والقالب.",
    content: "محتوى الصفحة",
    contentHint: "أدر عنوان التنقل والمحتوى التعريفي.",
    seo: "البحث والمشاركة",
    seoHint: "حدد عناوين وأوصافاً مترجمة لتحسين الظهور.",
    save: "نشر التغييرات",
    saving: "جارٍ الحفظ…",
    status: "الحالة",
    template: "القالب",
    sortOrder: "ترتيب العرض",
    homePage: "الصفحة الرئيسية الأساسية",
    homePageHint: "استخدم هذا المسار كصفحة الموقع الرئيسية.",
    titleLabel: "عنوان الصفحة",
    navigationLabel: "عنوان التنقل",
    excerpt: "المقدمة",
    metaTitle: "عنوان محركات البحث",
    metaDescription: "وصف محركات البحث",
    characters: "حرفاً",
    languageHint: "يُحفظ المحتوى بشكل مستقل لكل لغة مدعومة.",
    missing: "مسار الصفحة هذا غير موجود في نظام المحتوى.",
    noPages: "لم يتم العثور على صفحات.",
    previewRoute: "عرض المسار",
    en: "الإنجليزية",
    ar: "العربية",
    tr: "التركية",
  },
  tr: {
    title: "Web sitesi sayfaları",
    description: "Yayın, çevrilmiş içerik ve arama meta verilerini yönetmek için bir rota açın.",
    pages: "rota",
    published: "Yayında",
    draft: "Taslak",
    archived: "Arşivlendi",
    openEditor: "Düzenleyiciyi aç",
    lastUpdated: "Son güncelleme",
    back: "Tüm sayfalar",
    editorDescription: "Bu rotayı İngilizce, Arapça ve Türkçe olarak tek çalışma alanından yönetin.",
    general: "Yayınlama",
    generalHint: "Durum, sıralama ve şablon ayarlarını yönetin.",
    content: "Sayfa içeriği",
    contentHint: "Gezinme ve tanıtım metnini yönetin.",
    seo: "Arama ve paylaşım",
    seoHint: "Keşfedilebilirlik için yerelleştirilmiş başlık ve açıklamalar ekleyin.",
    save: "Değişiklikleri yayınla",
    saving: "Kaydediliyor…",
    status: "Durum",
    template: "Şablon",
    sortOrder: "Sıralama",
    homePage: "Birincil ana sayfa",
    homePageHint: "Bu rotayı web sitesinin ana sayfası olarak kullanın.",
    titleLabel: "Sayfa başlığı",
    navigationLabel: "Gezinme etiketi",
    excerpt: "Giriş",
    metaTitle: "SEO başlığı",
    metaDescription: "SEO açıklaması",
    characters: "karakter",
    languageHint: "İçerik desteklenen her dil için ayrı saklanır.",
    missing: "Bu sayfa rotası CMS içinde bulunamadı.",
    noPages: "Sayfa rotası bulunamadı.",
    previewRoute: "Rotayı görüntüle",
    en: "İngilizce",
    ar: "Arapça",
    tr: "Türkçe",
  },
};

export type PagesCopyText = PagesCopy;
