import type { Lang } from "@/context/global";

const en = {
  general: "General",
  visibility: "Publishing and visibility",
  languageHint: "Localized content",
  save: "Save",
  saving: "Saving...",
  publishing: "Published",
  draft: "Draft",
  archived: "Archived",
  badge: "Badge",
  eyebrow: "Eyebrow",
  heading: "Heading",
  subheading: "Subheading",
  chapterLabel: "Scroll tracker label",
  sectionContent: "Section content",
  sectionHint: "These fields feed the public route from the CMS API.",
  formContent: "Form content",
  liveChat: "Live chat",
  addScenario: "Add scenario",
  processSteps: "Process steps",
  addStep: "Add step",
  contactMethods: "Contact methods",
  addMethod: "Add method",
  officeInfo: "Office and location",
  companyLinks: "Company links",
  addLink: "Add link",
  remove: "Remove",
  label: "Label",
  status: "Status",
  intro: "Intro",
  title: "Title",
  description: "Description",
  id: "ID",
  prompt: "Prompt",
  userMessage: "User message",
  reply: "Reply",
  impact: "Impact",
  metric: "Metric",
  metricLabel: "Metric label",
  number: "Number",
  type: "Type",
  value: "Value",
  href: "Href",
  note: "Note",
  url: "URL",
  formTitle: "Form title",
  formSubtitle: "Form subtitle",
  privacyNote: "Privacy note",
  successTitle: "Success title",
  successMessage: "Success message",
  errorMessage: "Error message",
  botIntro: "Bot intro",
  action: "Action",
  sectionTitle: "Section title",
  officeTitle: "Office title",
  officeAddress: "Office address",
  officeNote: "Office note",
  bottomNotice: "Bottom notice",
  detailedLabels: "Additional template labels",
  addLabel: "Add label",
  reasons: "Reasons",
  addReason: "Add reason",
  icon: "Icon",
  quoteTitle: "Quote title",
  quoteText: "Quote text",
  hoverHint: "Hover hint",
  terminalLines: "Terminal lines",
  command: "Command",
  response: "Response",
  tone: "Color tone",
  addLine: "Add line",
  servicesList: "Services and tabs",
  addService: "Add service",
  serviceId: "Service ID",
  tabLabel: "Tab label",
  audience: "Audience",
  approach: "Approach",
  listTitle: "List title",
  listItems: "List items",
  addItem: "Add item",
  outcome: "Outcome",
  workModels: "Ways to work",
  addWorkModel: "Add work model",
  ctaText: "CTA text",
  ctaButton: "CTA button",
  toastMessage: "Confirmation message",
  bottomCta: "Bottom CTA",
  lifecycleSteps: "Lifecycle steps",
  addLifecycleStep: "Add lifecycle step",
  questions: "Questions",
  addQuestion: "Add question",
  options: "Options",
  addOption: "Add option",
  budget: "Budget",
  weeks: "Weeks",
  multiplier: "Budget multiplier",
  weekMultiplier: "Timeline multiplier",
  fieldPlaceholders: "Form field placeholders",
  projectDisplay: "Project display",
  emptyMessage: "Empty state message",
  statusLabels: "Project status labels",
  addStatus: "Add status label",
  caseStudies: "Case studies",
  addCaseStudy: "Add case study",
  commonItems: "Shared qualities",
  primaryButton: "Primary button",
  secondaryButton: "Secondary button",
  context: "Context",
  challenges: "Challenges",
  solution: "Solution",
  elements: "Key elements",
  results: "Results",
  addResult: "Add result",
  teamLabels: "Team display labels",
  careersForm: "Careers form",
  name: "Name",
  email: "Email",
  phone: "Phone",
  role: "Role",
  rolePlaceholder: "Role placeholder",
  linkedIn: "LinkedIn",
  placeholder: "Placeholder",
  portfolio: "Portfolio",
  cv: "CV upload",
  cvHint: "CV hint",
  submitting: "Submitting label",
  submit: "Submit label",
  previous: "Previous label",
  next: "Next label",
  openProfile: "Open profile label",
  closeProfile: "Close profile label",
  backToTeam: "Back to team label",
  memberLabel: "Member label",
} as const;

type RouteContentCopy = Record<keyof typeof en, string>;

export const ROUTE_CONTENT_COPY: Record<Lang, RouteContentCopy> = {
  en,
  ar: {
    general: "عام",
    visibility: "النشر والظهور",
    languageHint: "المحتوى المترجم",
    save: "حفظ",
    saving: "جارٍ الحفظ...",
    publishing: "منشور",
    draft: "مسودة",
    archived: "مؤرشف",
    badge: "الشارة",
    eyebrow: "النص العلوي",
    heading: "العنوان",
    subheading: "العنوان الفرعي",
    chapterLabel: "عنوان مؤشر التمرير",
    sectionContent: "محتوى القسم",
    sectionHint: "هذه الحقول تغذي الصفحة العامة من واجهة CMS.",
    formContent: "محتوى النموذج",
    liveChat: "المحادثة المباشرة",
    addScenario: "إضافة سيناريو",
    processSteps: "خطوات المتابعة",
    addStep: "إضافة خطوة",
    contactMethods: "طرق التواصل",
    addMethod: "إضافة طريقة",
    officeInfo: "المكتب والموقع",
    companyLinks: "روابط الشركة",
    addLink: "إضافة رابط",
    remove: "حذف",
    label: "التسمية",
    status: "الحالة",
    intro: "المقدمة",
    title: "العنوان",
    description: "الوصف",
    id: "المعرّف",
    prompt: "الخيار",
    userMessage: "رسالة المستخدم",
    reply: "الرد",
    impact: "الأثر",
    metric: "المؤشر",
    metricLabel: "تسمية المؤشر",
    number: "الرقم",
    type: "النوع",
    value: "القيمة",
    href: "الرابط",
    note: "ملاحظة",
    url: "الرابط",
    formTitle: "عنوان النموذج",
    formSubtitle: "وصف النموذج",
    privacyNote: "ملاحظة الخصوصية",
    successTitle: "عنوان النجاح",
    successMessage: "رسالة النجاح",
    errorMessage: "رسالة الخطأ",
    botIntro: "مقدمة الروبوت",
    action: "زر الإجراء",
    sectionTitle: "عنوان القسم",
    officeTitle: "عنوان المكتب",
    officeAddress: "عنوان المكتب",
    officeNote: "ملاحظة المكتب",
    bottomNotice: "الملاحظة السفلية",
    detailedLabels: "تسميات القالب الإضافية", addLabel: "إضافة تسمية", reasons: "الأسباب", addReason: "إضافة سبب", icon: "الأيقونة", quoteTitle: "عنوان الاقتباس", quoteText: "نص الاقتباس", hoverHint: "تلميح المرور", terminalLines: "أسطر النافذة الطرفية", command: "الأمر", response: "الاستجابة", tone: "درجة اللون", addLine: "إضافة سطر", servicesList: "الخدمات والتبويبات", addService: "إضافة خدمة", serviceId: "معرّف الخدمة", tabLabel: "عنوان التبويب", audience: "الجمهور", approach: "النهج", listTitle: "عنوان القائمة", listItems: "عناصر القائمة", addItem: "إضافة عنصر", outcome: "النتيجة", workModels: "طرق العمل", addWorkModel: "إضافة طريقة عمل", ctaText: "نص الإجراء", ctaButton: "زر الإجراء", toastMessage: "رسالة التأكيد", bottomCta: "الإجراء السفلي", lifecycleSteps: "مراحل العمل", addLifecycleStep: "إضافة مرحلة", questions: "الأسئلة", addQuestion: "إضافة سؤال", options: "الخيارات", addOption: "إضافة خيار", budget: "الميزانية", weeks: "الأسابيع", multiplier: "معامل الميزانية", weekMultiplier: "معامل المدة",
    fieldPlaceholders: "النصوص الإرشادية لحقول النموذج",
    projectDisplay: "عرض المشاريع", emptyMessage: "رسالة الحالة الفارغة", statusLabels: "تسميات حالات المشروع", addStatus: "إضافة تسمية حالة", caseStudies: "دراسات الحالة", addCaseStudy: "إضافة دراسة حالة", commonItems: "الخصائص المشتركة", primaryButton: "الزر الرئيسي", secondaryButton: "الزر الثانوي", context: "السياق", challenges: "التحديات", solution: "الحل", elements: "العناصر الرئيسية", results: "النتائج", addResult: "إضافة نتيجة", teamLabels: "تسميات عرض الفريق", careersForm: "نموذج الوظائف", name: "الاسم", email: "البريد الإلكتروني", phone: "الهاتف", role: "الدور", rolePlaceholder: "النص الإرشادي للدور", linkedIn: "لينكدإن", placeholder: "النص الإرشادي", portfolio: "معرض الأعمال", cv: "رفع السيرة الذاتية", cvHint: "ملاحظة السيرة الذاتية", submitting: "نص الإرسال", submit: "نص زر الإرسال", previous: "تسمية السابق", next: "تسمية التالي", openProfile: "تسمية فتح الملف", closeProfile: "تسمية إغلاق الملف", backToTeam: "تسمية العودة للفريق", memberLabel: "تسمية العضو",
  },
  tr: {
    general: "Genel",
    visibility: "Yayın ve görünürlük",
    languageHint: "Yerelleştirilmiş içerik",
    save: "Kaydet",
    saving: "Kaydediliyor...",
    publishing: "Yayında",
    draft: "Taslak",
    archived: "Arşivlendi",
    badge: "Rozet",
    eyebrow: "Üst etiket",
    heading: "Başlık",
    subheading: "Alt başlık",
    chapterLabel: "Kaydırma etiketi",
    sectionContent: "Bölüm içeriği",
    sectionHint: "Bu alanlar genel rotayı CMS API üzerinden besler.",
    formContent: "Form içeriği",
    liveChat: "Canlı sohbet",
    addScenario: "Senaryo ekle",
    processSteps: "Süreç adımları",
    addStep: "Adım ekle",
    contactMethods: "İletişim yöntemleri",
    addMethod: "Yöntem ekle",
    officeInfo: "Ofis ve konum",
    companyLinks: "Şirket bağlantıları",
    addLink: "Bağlantı ekle",
    remove: "Kaldır",
    label: "Etiket",
    status: "Durum",
    intro: "Giriş",
    title: "Başlık",
    description: "Açıklama",
    id: "ID",
    prompt: "Seçenek",
    userMessage: "Kullanıcı mesajı",
    reply: "Yanıt",
    impact: "Etki",
    metric: "Metrik",
    metricLabel: "Metrik etiketi",
    number: "Numara",
    type: "Tür",
    value: "Değer",
    href: "Bağlantı",
    note: "Not",
    url: "URL",
    formTitle: "Form başlığı",
    formSubtitle: "Form açıklaması",
    privacyNote: "Gizlilik notu",
    successTitle: "Başarı başlığı",
    successMessage: "Başarı mesajı",
    errorMessage: "Hata mesajı",
    botIntro: "Bot girişi",
    action: "Eylem",
    sectionTitle: "Bölüm başlığı",
    officeTitle: "Ofis başlığı",
    officeAddress: "Ofis adresi",
    officeNote: "Ofis notu",
    bottomNotice: "Alt not",
    detailedLabels: "Ek şablon etiketleri", addLabel: "Etiket ekle", reasons: "Nedenler", addReason: "Neden ekle", icon: "Simge", quoteTitle: "Alıntı başlığı", quoteText: "Alıntı metni", hoverHint: "Üzerine gelme ipucu", terminalLines: "Terminal satırları", command: "Komut", response: "Yanıt", tone: "Renk tonu", addLine: "Satır ekle", servicesList: "Hizmetler ve sekmeler", addService: "Hizmet ekle", serviceId: "Hizmet kimliği", tabLabel: "Sekme etiketi", audience: "Hedef kitle", approach: "Yaklaşım", listTitle: "Liste başlığı", listItems: "Liste öğeleri", addItem: "Öğe ekle", outcome: "Sonuç", workModels: "Çalışma yolları", addWorkModel: "Çalışma modeli ekle", ctaText: "Eylem metni", ctaButton: "Eylem düğmesi", toastMessage: "Onay mesajı", bottomCta: "Alt eylem", lifecycleSteps: "Yaşam döngüsü adımları", addLifecycleStep: "Adım ekle", questions: "Sorular", addQuestion: "Soru ekle", options: "Seçenekler", addOption: "Seçenek ekle", budget: "Bütçe", weeks: "Hafta", multiplier: "Bütçe çarpanı", weekMultiplier: "Süre çarpanı",
    fieldPlaceholders: "Form alanı yer tutucuları",
    projectDisplay: "Proje görünümü", emptyMessage: "Boş durum mesajı", statusLabels: "Proje durum etiketleri", addStatus: "Durum etiketi ekle", caseStudies: "Vaka çalışmaları", addCaseStudy: "Vaka çalışması ekle", commonItems: "Ortak nitelikler", primaryButton: "Birincil düğme", secondaryButton: "İkincil düğme", context: "Bağlam", challenges: "Zorluklar", solution: "Çözüm", elements: "Temel öğeler", results: "Sonuçlar", addResult: "Sonuç ekle", teamLabels: "Ekip görünüm etiketleri", careersForm: "Kariyer formu", name: "Ad", email: "E-posta", phone: "Telefon", role: "Rol", rolePlaceholder: "Rol yer tutucusu", linkedIn: "LinkedIn", placeholder: "Yer tutucu", portfolio: "Portföy", cv: "CV yükleme", cvHint: "CV ipucu", submitting: "Gönderiliyor etiketi", submit: "Gönder düğmesi", previous: "Önceki etiketi", next: "Sonraki etiketi", openProfile: "Profil aç etiketi", closeProfile: "Profil kapat etiketi", backToTeam: "Ekibe dön etiketi", memberLabel: "Üye etiketi",
  },
};

export type RouteContentCopyText = RouteContentCopy;
