import type { Lang } from "@/context/global";
import type { ApplicationStatus } from "./types";

const en = {
  title: "Job requests",
  description: "Review applications, download CVs, and move candidates through the hiring process.",
  search: "Search name, email, phone, or custom title",
  allStatuses: "All statuses",
  inbox: "Applications",
  role: "Job title",
  received: "Received",
  phone: "Phone",
  email: "Email",
  links: "Candidate links",
  linkedIn: "LinkedIn",
  portfolio: "Portfolio",
  coverNote: "Cover note",
  noCoverNote: "No cover note was provided.",
  status: "Status",
  notes: "Internal notes",
  notesHint: "Add private recruiting notes…",
  save: "Save changes",
  saving: "Saving…",
  reply: "Email candidate",
  downloadCv: "Download CV",
  downloading: "Downloading…",
  review: "Review",
  empty: "No applications match these filters.",
  choose: "Choose an application to review the candidate.",
  result: "application",
  results: "applications",
  new: "New",
  reviewing: "Reviewing",
  shortlisted: "Shortlisted",
  interview: "Interview",
  offered: "Offer sent",
  hired: "Hired",
  rejected: "Rejected",
  archived: "Archived",
} as const;

type ApplicationsCopy = Record<keyof typeof en, string>;

export const JOB_APPLICATIONS_COPY: Record<Lang, ApplicationsCopy> = {
  en,
  ar: {
    title: "طلبات التوظيف",
    description: "راجع الطلبات ونزّل السير الذاتية وتابع المرشحين خلال مراحل التوظيف.",
    search: "ابحث بالاسم أو البريد أو الهاتف أو المسمى",
    allStatuses: "جميع الحالات",
    inbox: "طلبات التوظيف",
    role: "المسمى الوظيفي",
    received: "تاريخ الاستلام",
    phone: "الهاتف",
    email: "البريد الإلكتروني",
    links: "روابط المرشح",
    linkedIn: "لينكدإن",
    portfolio: "معرض الأعمال",
    coverNote: "نبذة المتقدم",
    noCoverNote: "لم يرفق المتقدم نبذة إضافية.",
    status: "الحالة",
    notes: "ملاحظات داخلية",
    notesHint: "أضف ملاحظات خاصة بفريق التوظيف…",
    save: "حفظ التغييرات",
    saving: "جارٍ الحفظ…",
    reply: "مراسلة المرشح",
    downloadCv: "تنزيل السيرة الذاتية",
    downloading: "جارٍ التنزيل…",
    review: "مراجعة",
    empty: "لا توجد طلبات تطابق عوامل التصفية.",
    choose: "اختر طلباً لمراجعة بيانات المرشح.",
    result: "طلب",
    results: "طلبات",
    new: "جديد",
    reviewing: "قيد المراجعة",
    shortlisted: "ضمن القائمة المختصرة",
    interview: "مقابلة",
    offered: "تم إرسال العرض",
    hired: "تم التوظيف",
    rejected: "مرفوض",
    archived: "مؤرشف",
  },
  tr: {
    title: "İş başvuruları",
    description: "Başvuruları inceleyin, özgeçmişleri indirin ve adayları işe alım sürecinde takip edin.",
    search: "Ad, e-posta, telefon veya unvan ara",
    allStatuses: "Tüm durumlar",
    inbox: "Başvurular",
    role: "İş unvanı",
    received: "Alındı",
    phone: "Telefon",
    email: "E-posta",
    links: "Aday bağlantıları",
    linkedIn: "LinkedIn",
    portfolio: "Portföy",
    coverNote: "Ön yazı",
    noCoverNote: "Ön yazı eklenmedi.",
    status: "Durum",
    notes: "Dahili notlar",
    notesHint: "Özel işe alım notları ekleyin…",
    save: "Değişiklikleri kaydet",
    saving: "Kaydediliyor…",
    reply: "Adaya e-posta gönder",
    downloadCv: "CV indir",
    downloading: "İndiriliyor…",
    review: "İncele",
    empty: "Bu filtrelere uyan başvuru yok.",
    choose: "Adayı incelemek için bir başvuru seçin.",
    result: "başvuru",
    results: "başvuru",
    new: "Yeni",
    reviewing: "İnceleniyor",
    shortlisted: "Kısa listede",
    interview: "Mülakat",
    offered: "Teklif gönderildi",
    hired: "İşe alındı",
    rejected: "Reddedildi",
    archived: "Arşivlendi",
  },
};

const statusKeys: Record<ApplicationStatus, keyof ApplicationsCopy> = {
  NEW: "new",
  REVIEWING: "reviewing",
  SHORTLISTED: "shortlisted",
  INTERVIEW: "interview",
  OFFERED: "offered",
  HIRED: "hired",
  REJECTED: "rejected",
  ARCHIVED: "archived",
};

export function applicationStatusLabel(copy: ApplicationsCopy, status: ApplicationStatus) {
  return copy[statusKeys[status]];
}

export type JobApplicationsCopyText = ApplicationsCopy;
